name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    env:
      NODE_ENV: test
      SUPABASE_URL: https://fake-supabase-url.supabase.co
      SUPABASE_KEY: fake-supabase-key-for-testing
      SLACK_BOT_TOKEN: xoxb-fake-token-for-testing
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Run tests
      run: yarn test
      env:
        SUPABASE_URL: https://fake-project.supabase.co
        SUPABASE_KEY: fake-anon-key-for-testing
        SLACK_BOT_TOKEN: xoxb-fake-token-for-testing
        SLACK_CLIENT_ID: fake-client-id-for-testing
        SLACK_CLIENT_SECRET: fake-client-secret-for-testing
        BASE_URL: https://test-app.example.com
        NODE_ENV: test
